DROP TABLE IF EXISTS HSKVOCAB;
CREATE TABLE HSKVOCAB(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    simplified NVARCHAR NOT NULL,
    traditional TEXT NOT NULL,
    pinyinnumbers TEXT NOT NULL,
    pinyintones TEXT NOT NULL,
    definition TEXT NOT NULL,
    hsklevel INTEGER NOT NULL
);

DROP TABLE IF EXISTS CUSTOMWORDS;
CREATE TABLE CUSTOMWORDS(
    wordid FOREIGN KEY REFERENCES HSKVOCAB(id)
)